project_id = "ymddtgbsybvxfitgupqy"

[functions.sync-wallet-balance]
verify_jwt = false

[functions.send-crypto-payment] 
verify_jwt = false

[functions.generate-ifrs-report]
verify_jwt = false

[functions.calculate-us-tax]
verify_jwt = false